DELETE FROM [Employee];
SET IDENTITY_INSERT[Employee] ON;
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(1,'InezFionaSutanto','JWT',1,'InezFiona.Sutanto@mitrais.com','mitrais\Inez_S',1,1,'Sanur_2017!','a');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(2,'Billy Christi Hartanto','JWT',1,'BillyChristi.Hartanto@mitrais.com','mitrais\Billy_J',1,1,'Sanur_2017!','b');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(3,'Wimba Agra Wicesa','JWT',1,'WimbaAgra.Wicesa@mitrais.com','mitrais\Wimba_W',1,1,'Sanur_2017!','c');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(4,'I Gede Wisesa Priya Fentika','JWT',1,'IGedeWisesaPriya.Fentika@mitrais.com','mitrais\Wisesa_F',1,1,'Sanur_2017!','d');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(5,'Daniel Muliawan','JWT',1,'Daniel.Muliawan@mitrais.com','mitrais\Daniel_M',1,1,'Sanur_2017!','e');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(6,'Deny Sufriawan','JWT',1,'Deny.Sufriawan@mitrais.com','mitrais\Denny_S',1,1,'Sanur_2017!','f');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(7,'Yuliawan Rizka Syafaat','JWT',1,'YuliawanRizka.Syafaat@mitrais.com','mitrais\Yulian_S',1,1,'Sanur_2017!','g');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(8,'Sopyan Mulyana','JWT',1,'Sopyan.Mulyana@mitrais.com','mitrais\Sopyan_M',1,1,'Sanur_2017!','h');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(9,'Ibnu Prayogi','JWT',1,'Ibnu.Prayogi@mitrais.com','mitrais\Ibnu_P',1,1,'Sanur_2017!','i');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(10,'Taufik Adrian','JWT',1,'MohammadTaufik.Andrian@mitrais.com','mitrais\Taufik_A',1,1,'Sanur_2017!','j');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(11,'Kenny Summerfield','AJAX',1,'Renny.Summerfield@mitrais.com','mitrais\Renny_S',3,2,'Sanur_2017!','k');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(12,'Pajero Sport','JSON',1,'Pajero.Sport@mitrais.com','mitrais\Pajero_S',14,2,'Sanur_2017!','l');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(13,'Lulu Lalala','Node JS',1,'Lulu.Lalala@mitrais.com','mitrais\Lulu_L',11,4,'Sanur_2017!','m');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(14,'James Dean','CSS',1,'James.Dean@mitrais.com','mitrais\James_D',4,1,'Sanur_2017!','n');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(15,'Tinky Winky','C#',1,'Tinky.Winky@mitrais.com','mitrais\Tinky_W',15,1,'Sanur_2017!','o');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(16,'Coco Nucifera','C++',1,'Coco.Nucifera@mitrais.com','mitrais\Coco_N',15,2,'Sanur_2017!','p');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(17,'Theobroma Cacao','JSON',0,'Theobroma.Cacao@mitrais.com','mitrais\Theo_C',11,1,'Sanur_2017!','q');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(18,'Apis Melliferra','Java',1,'Apis.Mellifera@mitrais.com','mitrais\Apis_M',3,1,'Sanur_2017!','r');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(19,'Felis Silvester','Java Script',1,'Felis.Silvester@mitrais.com','mitrais\Felis_S',15,3,'Sanur_2017!','s');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(20,'Papillon Spaniel','PHP',1,'Papillon.Spaniel@mitrais.com','mitrais\Papillon_S',6,2,'Sanur_2017!','t');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(21,'Marie Curie','Haskell',1,'Marie.Curie@mitrais.com','mitrais\Marie_C',4,1,'Sanur_2017!','u');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(22,'John Tralala','Lisp',1,'John.Tralala@mitrais.com','mitrais\John_T',12,2,'Sanur_2017!','v');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(23,'Johnny Depp','HTML',1,'Johnny.Depp@mitrais.com','mitrais\Johnny_D',2,2,'Sanur_2017!','w');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(24,'Jhonny Not Depp','PHP',1,'JhonnyNot.Depp@mitrais.com','mitrais\Jhonny_D',1,1,'Sanur_2017!','x');
INSERT INTO [Employee](EmployeeID, FullName, Stream, ActiveEmployee, Email, AccountName, GradeID, LocationID, AccountPassword,Salt)VALUES(25,'Joni Derp','Java',1,'Joni.Derp@mitrais.com','mitrais\Joni_D',14,4,'Sanur_2017!','y');

SET IDENTITY_INSERT [Employee] OFF